services:
  mysql:
    image: mysql:8.0
    container_name: dilowa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-dilowa_admiN25}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dilowa-db}
      MYSQL_ROOT_HOST: '%'
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/dilowa-db.sql:/docker-entrypoint-initdb.d/dilowa-db.sql
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dilowa-backend
    env_file:
      - ./backend/.env.development 
    environment:
      - CLIENT_ORIGIN=http://localhost:8080
      - DATABASE_URL=mysql://root:dilowa_admiN25@mysql:3306/dilowa-db
    depends_on:
      - mysql
    ports:
      - "3001:3001"
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: /api
    container_name: dilowa-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: on-failure

volumes:
  mysql_data:
    driver: local