services:
  mysql:
    image: mysql:8.0
    container_name: dilowa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: dilowa_admiN25   # Passwort für den root-Admin
      MYSQL_DATABASE: dilowa-db            # Die Datenbank, die beim Start erstellt wird
      MYSQL_ROOT_HOST: '%'
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password  # Optional, falls du mysql_native_password benötigst
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
    driver: local
